default: &default
 adapter: postgresql
 user: addstock
 password: addstock
 pool: 5
 timeout: 5000
 host: localhost

development:
  <<: *default
  database: addstock_development

test:
  <<: *default
  database: addstock_test

production:
  <<: *default
  database: addstock_production
